version: '3'
services:
  database:
    build: './backend/database'
    ports:
      - 3306:3306
    networks:
      - database
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-volume:/var/lib/mysql
  backend:
    build: './backend/api'
    ports:
      - 3001:3001
    depends_on:
      - database
    networks:
      - database
      - backend
      - frontend
    volumes:
      - backend-volume:/var/lib/backend
    environment:
      - MYSQL_HOST=database
      - MYSQL_DB_NAME=noteDB
      - MYSQL_ROOT_PASSWORD=root
  frontend:
    build: './frontend-react'
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - frontend
networks:
  backend:
  frontend:
  database:
volumes:
  db-volume:
  backend-volume: